<?php
return [
  [
    'module'  => 'adyen',
    'name'    => 'adyen_notification_event_code',
    'entity'  => 'OptionGroup',
    'cleanup' => 'never',
    'params'  => [
      'version'   => 3,
      'name'      => 'adyen_notification_event_code',
      'title'     => 'Adyen Notification Event Code',
      'data_type' => 'Integer',
      'is_active' => 1,
    ],
  ],
  [
    'module'  => 'adyen',
    'name'    => 'adyen_notification_status',
    'entity'  => 'OptionGroup',
    'cleanup' => 'never',
    'params'  => [
      'version'   => 3,
      'name'      => 'adyen_notification_status',
      'title'     => 'Adyen Notification Status',
      'data_type' => 'Integer',
      'is_active' => 1,
    ],
  ],
  [
    'module'  => 'adyen',
    'name'    => 'adyen_notification_event_code_report_available',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'adyen_notification_event_code',
      'value'           => 1,
      'name'            => 'report_available',
      'label'           => 'Report Available',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'adyen',
    'name'    => 'adyen_notification_status_pending',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'adyen_notification_status',
      'value'           => 1,
      'name'            => 'pending',
      'label'           => 'Pending',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'adyen',
    'name'    => 'adyen_notification_status_in_progress',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'adyen_notification_status',
      'value'           => 2,
      'name'            => 'in_progress',
      'label'           => 'In Progress',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'adyen',
    'name'    => 'adyen_notification_status_completed',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'adyen_notification_status',
      'value'           => 3,
      'name'            => 'completed',
      'label'           => 'Completed',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'adyen',
    'name'    => 'adyen_notification_status_ignored',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'adyen_notification_status',
      'value'           => 4,
      'name'            => 'ignored',
      'label'           => 'Ignored',
      'is_active'       => 1,
    ],
  ],
];
