-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_adyen_report_line`;
DROP TABLE IF EXISTS `civicrm_adyen_notification`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_adyen_notification
-- *
-- * List of Adyen notifications received via webhooks
-- *
-- *******************************************************/
CREATE TABLE `civicrm_adyen_notification` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique AdyenNotification ID',
     `event_code_id` int unsigned NOT NULL   COMMENT 'ID of event code',
     `event_date` datetime NOT NULL   COMMENT 'Date of the event',
     `psp_reference` varchar(255) NOT NULL   COMMENT 'PSP Reference',
     `merchant_account` varchar(80) NOT NULL   COMMENT 'Merchant Account',
     `processing_order` int unsigned NULL   COMMENT 'Processing Order',
     `status_id` int unsigned NOT NULL  DEFAULT 1 COMMENT 'ID of notification status',
     `notification` longtext NOT NULL   COMMENT 'Adyen NotificationRequestItem (JSON)' 
,
        PRIMARY KEY (`id`)
 
 
 
)    ;

-- /*******************************************************
-- *
-- * civicrm_adyen_report_line
-- *
-- * List of lines in an Adyen report
-- *
-- *******************************************************/
CREATE TABLE `civicrm_adyen_report_line` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique AdyenReportLine ID',
     `adyen_notification_id` int unsigned    COMMENT 'FK to AdyenNotification',
     `line_number` int unsigned NOT NULL   COMMENT 'Line number in report file',
     `line_date` datetime NULL   COMMENT 'Date of the line',
     `content` longtext NOT NULL   COMMENT 'Adyen Report Line (JSON)',
     `status_id` int unsigned NOT NULL  DEFAULT 1 COMMENT 'ID of report line status' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `UI_adyen_notification_line_number`(
        adyen_notification_id
      , line_number
  )
  
,          CONSTRAINT FK_civicrm_adyen_report_line_adyen_notification_id FOREIGN KEY (`adyen_notification_id`) REFERENCES `civicrm_adyen_notification`(`id`) ON DELETE CASCADE  
)    ;

 
